# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: id_rsa
instance_flavor: uom.general.2c8g
# instance_network: qh2-uom-internal

# Volume
volumes:
  - vol_name: demo-03-vol-1
    vol_size: 10
  - vol_name: demo-03-vol-2
    vol_size: 10

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: demo-03
    volumes: ["demo-03-vol-1", "demo-03-vol-2"]
