- hosts: Wordpress
  vars_files:
    - host_vars/wordpress.yaml
  gather_facts: false
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/id_rsa
    - ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
    - role: common
    - role: volumes
    - role: docker
    - role: wordpress
