---
- name: Uninstall old versions of docker
  become: true
  ansible.builtin.apt:
    name: ["docker", "docker-engine", "docker.io", "containerd", "runc"]
    state: absent

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      [
        "apt-transport-https",
        "build-essential",
        "ca-certificates",
        "curl",
        "git",
        "gnupg",
        "gnupg-agent",
        "lsb-release",
        "python3-dev",
        "python3-pip",
        "python3-setuptools",
        "snapd",
        "software-properties-common",
        "unzip",
      ]
    state: latest
    install_recommends: false
    update_cache: true

- name: Add Docker’s official GPG key
  become: true
  ansible.builtin.shell: |
    rm -rf /etc/apt/keyrings/docker.gpg
    mkdir -m 0755 -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

- name: Add set up Docker apt_repository
  become: true
  ansible.builtin.shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install docker
  become: true
  ansible.builtin.apt:
    name:
      [
        "docker-ce",
        "docker-ce-cli",
        "containerd.io",
        "docker-buildx-plugin",
        "docker-compose-plugin",
      ]
    state: latest
    install_recommends: false
    update_cache: true

- name: Install docker-compose V1
  become: true
  ansible.builtin.pip:
    name: ["docker-compose"]
    state: latest
